#!/bin/sh
#
# Script to build container image.
#

SCRIPT_DIR=$(cd -- "$(dirname -- "${0}")" && pwd)
. "${SCRIPT_DIR}/inc.functions"

# Default values
DEFAULT_ANDROID=$(grep android= "${SCRIPT_DIR}/../Dockerfile" | cut -d"=" -f2)
DEFAULT_CMAKE=$(grep cmake= "${SCRIPT_DIR}/../Dockerfile" | cut -d"=" -f2)
DEFAULT_JDK=$(grep jdk= "${SCRIPT_DIR}/../Dockerfile" | cut -d"=" -f2)
DEFAULT_NDK=$(grep ndk= "${SCRIPT_DIR}/../Dockerfile" | cut -d"=" -f2)
DEFAULT_PLATFORMS="linux/amd64"
DEFAULT_TOOL=$( (command -v docker || command -v podman) | grep -o '[^/]*$')

# Functions
usage() {
  printf "Usage: %s [OPTIONS]\n" "${0}"
  printf "Options:\n"
  printf "  --android API_LEVEL (default: %s)\n" "${DEFAULT_ANDROID}"
  printf "  --cmake VERSION     (default: %s)\n" "${DEFAULT_CMAKE}"
  printf "  --container         (optional, build with Apple Container)\n"
  printf "  --jdk VERSION       (default: %s)\n" "${DEFAULT_JDK}"
  printf "  --ndk VERSION       (default: %s)\n" "${DEFAULT_NDK}"
  printf "  --docker            (optional, build with Docker)\n"
  printf "  --platforms         (default: %s)\n" "${DEFAULT_PLATFORMS}"
  printf "  --podman            (optional, build with Podman)\n"
  printf "  --push              (optional, upload images to Docker Hub)\n"
  printf "  --verbose           (optional)\n"
  exit 1
}

# Command-line arguments
android="${DEFAULT_ANDROID}"
cmake="${DEFAULT_CMAKE}"
jdk="${DEFAULT_JDK}"
ndk="${DEFAULT_NDK}"
platforms="${DEFAULT_PLATFORMS}"
cmd_push=
progress=auto
tool="${DEFAULT_TOOL}"
while [ $# -gt 0 ]; do
  key="$1"
  case $key in
  --android) android="$2" shift ;;
  --cmake) cmake="$2" shift ;;
  --container) tool="container" ;;
  --docker) tool="docker" ;;
  --jdk) jdk="$2" shift ;;
  --ndk) ndk="$2" shift ;;
  --platforms) platforms="$2" shift ;;
  --podman) tool="podman" ;;
  --push) cmd_push=true ;;
  --verbose) progress=plain ;;
  -h | --help) usage ;;
  *) ;;
  esac
  shift # past argument or value
done

# Let's roll
image_tag="saschpe/android-ndk:${android}-jdk${jdk}-ndk${ndk}-cmake${cmake}"

if [ ${cmd_push} ]; then
  approve "Build and push image '${image_tag}' with ${tool}"
  push_command="--push"
else
  approve "Build image '${image_tag}' with ${tool}"
fi

safe "${tool}" build \
  --build-arg android="${android}" \
  --build-arg cmake="${cmake}" \
  --build-arg jdk="${jdk}" \
  --build-arg ndk="${ndk}" \
  --platform "${platforms}" \
  --progress "${progress}" \
  ${push_command} \
  --tag "${image_tag}" \
  .
