name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  IMAGE: saschpe/android-ndk
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  buildx:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        jdk: [ 17.0.13_11, 21.0.5_11, 22.0.2_9 ]
        android: [ 34, 35 ]
        ndk: [ 26.3.11579264, 27.2.12479018 ]
        cmake: [ 3.31.1 ]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE }}
            ghcr.io/${{ env.IMAGE }}
          tags: |
            type=raw,value=${{ matrix.android }}-jdk${{ matrix.jdk }}-ndk${{ matrix.ndk }}-cmake${{ matrix.cmake }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Github Container Repository
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            jdk=${{ matrix.jdk }} 
            android=${{ matrix.android }}
            ndk=${{ matrix.ndk }}
            cmake=${{ matrix.cmake }}
          provenance: ${{ github.event_name != 'pull_request' }}
          sbom: ${{ github.event_name != 'pull_request' }}
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline
      - name: Update Docker Hub repository description
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.IMAGE }}
          short-description: ${{ github.event.repository.description }}
